---
- name: "DISA RHEL-07-030340: Configure auditd space_left Action on Low Disk Space"
  lineinfile:
    dest: /etc/audit/auditd.conf
    line: "space_left_action = {{ var_auditd_space_left_action }}"
    regexp: '^\s*space_left_action\s*=\s*.*$'
    state: present
  tags:
    - cat II
...