---
- name: "DISA RHEL-07-010060: Set Session Screen Lock"
  ini_file:
    path: /etc/dconf/db/local.d/00-security-settings
    section: org/gnome/desktop/screensaver
    option: lock-enable
    value: True
  tags:
  - Cat II
...