---
- name: "DISA-STIG-RHEL-07-040370: Disable SSH Root Login"
  lineinfile:
    create: yes
    dest: "/etc/ssh/sshd_config"
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    insertafter: '(?i)^#?authentication'
    validate: /usr/sbin/sshd -t -f %s
  #notify: restart sshd
  tags:
    - cat II
...
