---
- name: "DISA RHEL-07-010330: Add auth pam_faillock preauth even_deny_root before pam_unix.so"
  pamd:
    name: "{{ item }}"
    type: auth
    control: sufficient
    module_path: pam_unix.so
    new_type: auth
    new_control: required
    new_module_path: pam_faillock.so
    module_arguments: 'preauth
        silent
        even_deny_root'
    state: before
  loop:
    - system-auth
    - password-auth
  tags:
    - cat II

- name: "DISA RHEL-07-010330: Add even_deny_root argument to auth pam_faillock preauth"
  pamd:
    name: "{{ item }}"
    type: auth
    control: required
    module_path: pam_faillock.so
    module_arguments: 'preauth
        silent
        even_deny_root'
    state: args_present
  loop:
    - system-auth
    - password-auth
  tags:
    - cat II

- name: "DISA RHEL-07-010330: Add auth pam_faillock authfail even_deny_root after pam_unix.so"
  pamd:
    name: "{{ item }}"
    type: auth
    control: sufficient
    module_path: pam_unix.so
    new_type: auth
    new_control: '[default=die]'
    new_module_path: pam_faillock.so
    module_arguments: 'authfail
        even_deny_root'
    state: after
  loop:
    - system-auth
    - password-auth
  tags:
    - cat II

- name: "DISA RHEL-07-010330: Add even_deny_root argument to auth pam_faillock authfail"
  pamd:
    name: "{{ item }}"
    type: auth
    control: '[default=die]'
    module_path: pam_faillock.so
    module_arguments: 'authfail
        even_deny_root'
    state: args_present
  loop:
    - system-auth
    - password-auth
  tags:
    - cat II

- name: "DISA RHEL-07-010330: Add account pam_faillock before pam_unix.so"
  pamd:
    name: "{{ item }}"
    type: account
    control: required
    module_path: pam_unix.so
    new_type: account
    new_control: required
    new_module_path: pam_faillock.so
    state: before
  loop:
    - system-auth
    - password-auth
  tags:
    - cat II
...