---
- name: "DISA RHEL-07-030780: Search /etc/audit/rules.d for ssh_keysign audit rule entries"
  find:
    paths: "/etc/audit/rules.d"
    recurse: no
    contains: "^.*path=/usr/libexec/openssh/ssh-keysign.*$"
    patterns: "*.rules"
  register: find_ssh_keysign
  tags:
    - cat II

- name: "DISA RHEL-07-030780: Use /etc/audit/rules.d/privileged.rules as the recipient for the rule"
  set_fact:
    all_files:
      - /etc/audit/rules.d/privileged.rules
  when: find_ssh_keysign.matched == 0 and True
  tags:
    - cat II

- name: "DISA RHEL-07-030780: Use matched file as the recipient for the rule"
  set_fact:
    all_files:
      - "{{ find_ssh_keysign.files | map(attribute='path') | list | first }}"
  when: find_ssh_keysign.matched > 0 and True
  tags:
    - cat II

- name: "DISA RHEL-07-030780: Inserts/replaces the ssh_keysign rule in rules.d"
  lineinfile:
    path: "{{ all_files[0] }}"
    line: "-a always,exit -F path=/usr/libexec/openssh/ssh-keysign -F perm=x -F auid>=1000 -F auid!=unset -F key=privileged"
    create: yes
  tags:
    - cat II

- name: "DISA RHEL-07-030780: Inserts/replaces the ssh_keysign rule in /etc/audit/audit.rules"
  lineinfile:
    path: /etc/audit/audit.rules
    line: "-a always,exit -F path=/usr/libexec/openssh/ssh-keysign -F perm=x -F auid>=1000 -F auid!=unset -F key=privileged"
    create: yes
  tags:
    - cat II
...   