---
- name: "Disable GDM Guest Login"
  ini_file:
    path: /etc/gdm/custom.conf
    section: daemon
    option: TimedLoginEnable
    value: "false"
    no_extra_spaces: yes
    create: yes
  when: gui_present
  tags:
    - cat I
...