---
- name: "DISA RHEL-07-021020: Get nfs and nfs4 mount points, that don't have nosuid"
  shell: grep -E "[[:space:]]nfs[4]?[[:space:]]" /etc/fstab | grep -v "nosuid" | awk '{print $2}'
  register: points_register
  check_mode: no
  changed_when: False
  tags:
    - cat II

- name: "DISA RHEL-07-021020: Add nosuid to mount points"
  shell: awk '$2=="{{ item }}"{$4=$4",nosuid"}1' /etc/fstab > fstab.tmp && mv fstab.tmp /etc/fstab
  with_items:
    - "{{ points_register.stdout_lines }}"
  when: (points_register.stdout | length > 0) and True
...      