---
- name: "DISA-STIG-RHEL-07-030821: Use /etc/audit/rules.d/privileged.rules as the recipient for the rule "
  set_fact:
    all_files:
      - /etc/audit/rules.d/privileged.rules
  when:
    - find_finit_module.matched is defined and find_finit_module.matched == 0
  tags:
    - cat II

- name: "DISA-STIG-RHEL-07-030821: Use matched file as the recipient for the rule"
  set_fact:
    all_files:
      - '{{ find_finit_module.files | map(attribute=''path'') | list | first }}'
  when:
    - find_finit_module.matched is defined and find_finit_module.matched > 0
  tags:
    - cat II

- name: "DISA-STIG-RHEL-07-030821: Inserts/replaces the finit_module rule in rules.d"
  lineinfile:
    path: '{{ all_files[0] }}'
    line: -a always,exit -F arch=b32 -S finit_module -k module-change
    state: present
    create: true
  tags:
    - cat II

- name: "DISA-STIG-RHEL-07-030821: Inserts/replaces the finit_module rule in rules.d on x86_64"
  lineinfile:
    path: '{{ all_files[0] }}'
    line: -a always,exit -F arch=b64 -S finit_module -k module-change
    state: present
    create: true
  when:
    - audit_arch is defined and audit_arch == 'b64'
  tags:
    - cat II

- name: "DISA-STIG-RHEL-07-030821: Inserts/replaces the finit_module rule in audit.rules"
  lineinfile:
    path: /etc/audit/audit.rules
    line: -a always,exit -F arch=b32 -S finit_module -k module-change
    create: true
  tags:
    - cat II

- name: "DISA-STIG-RHEL-07-030821: Inserts/replaces the finit_module rule in audit.rules when on x86_64"
  lineinfile:
    path: /etc/audit/audit.rules
    line: -a always,exit -F arch=b64 -S finit_module -k module-change
    create: true
  when:
    - audit_arch is defined and audit_arch == 'b64'
  tags:
    - cat II
...
