---
- name: "DISA RHEL-07-010320: Add auth pam_faillock preauth unlock_time before pam_unix.so"
  pamd:
    name: "{{ item }}"
    type: auth
    control: sufficient
    module_path: pam_unix.so
    new_type: auth
    new_control: required
    new_module_path: pam_faillock.so
    module_arguments: 'preauth
        silent
        unlock_time={{ var_accounts_passwords_pam_faillock_unlock_time }}'
    state: before
  loop:
    - system-auth
    - password-auth
  tags:
    - cat II

- name: "DISA RHEL-07-010320: Add unlock_time argument to pam_faillock preauth"
  pamd:
    name: "{{ item }}"
    type: auth
    control: required
    module_path: pam_faillock.so
    module_arguments: 'preauth
        silent
        unlock_time={{ var_accounts_passwords_pam_faillock_unlock_time }}'
    state: args_present
  loop:
    - system-auth
    - password-auth
  tags:
    - cat II

- name: "DISA RHEL-07-010320: Add auth pam_faillock authfail unlock_interval after pam_unix.so"
  pamd:
    name: "{{ item }}"
    type: auth
    control: sufficient
    module_path: pam_unix.so
    new_type: auth
    new_control: '[default=die]'
    new_module_path: pam_faillock.so
    module_arguments: 'authfail
        unlock_time={{ var_accounts_passwords_pam_faillock_unlock_time }}'
    state: after
  loop:
    - system-auth
    - password-auth
  tags:
    - cat II

- name: "DISA RHEL-07-010320: Add unlock_time argument to auth pam_faillock authfail"
  pamd:
    name: "{{ item }}"
    type: auth
    control: '[default=die]'
    module_path: pam_faillock.so
    module_arguments: 'authfail
        unlock_time={{ var_accounts_passwords_pam_faillock_unlock_time }}'
    state: args_present
  loop:
    - system-auth
    - password-auth
  tags:
    - cat II

- name: "DISA RHEL-07-010320: Add account pam_faillock before pam_unix.so"
  pamd:
    name: "{{ item }}"
    type: account
    control: required
    module_path: pam_unix.so
    new_type: account
    new_control: required
    new_module_path: pam_faillock.so
    state: before
  loop:
    - system-auth
    - password-auth
  tags:
    - cat II

- name: "DISA RHEL-07-010320: Add auth pam_faillock preauth fail_interval before pam_unix.so"
  pamd:
    name: "{{ item }}"
    type: auth
    control: sufficient
    module_path: pam_unix.so
    new_type: auth
    new_control: required
    new_module_path: pam_faillock.so
    module_arguments: 'preauth
        silent
        fail_interval={{ var_accounts_passwords_pam_faillock_fail_interval }}'
    state: before
  loop:
    - system-auth
    - password-auth
  tags:
    - cat II

- name: "DISA RHEL-07-010320: Add fail_interval argument to auth pam_faillock preauth"
  pamd:
    name: "{{ item }}"
    type: auth
    control: required
    module_path: pam_faillock.so
    module_arguments: 'preauth
        silent
        fail_interval={{ var_accounts_passwords_pam_faillock_fail_interval }}'
    state: args_present
  loop:
    - system-auth
    - password-auth
  tags:
    - cat II

- name: "DISA RHEL-07-010320: Add auth pam_faillock aufthfail fail_interval after pam_unix.so"
  pamd:
    name: "{{ item }}"
    type: auth
    control: sufficient
    module_path: pam_unix.so
    new_type: auth
    new_control: '[default=die]'
    new_module_path: pam_faillock.so
    module_arguments: 'authfail
        fail_interval={{ var_accounts_passwords_pam_faillock_fail_interval }}'
    state: after
  loop:
    - system-auth
    - password-auth
  tags:
    - cat II

- name: "DISA RHEL-07-010320: Add fail_interval argument to auth pam_faillock authfail"
  pamd:
    name: "{{ item }}"
    type: auth
    control: '[default=die]'
    module_path: pam_faillock.so
    module_arguments: 'authfail
        fail_interval={{ var_accounts_passwords_pam_faillock_fail_interval }}'
    state: args_present
  loop:
    - system-auth
    - password-auth
  tags:
    - cat II

- name: "DISA RHEL-07-010320: Add account pam_faillock before pam_unix.so"
  pamd:
    name: "{{ item }}"
    type: account
    control: required
    module_path: pam_unix.so
    new_type: account
    new_control: required
    new_module_path: pam_faillock.so
    state: before
  loop:
    - system-auth
    - password-auth
  tags:
    - cat II

- name: "DISA RHEL-07-010320: Add auth pam_faillock preauth deny before pam_unix.so"
  pamd:
    name: "{{ item }}"
    type: auth
    control: sufficient
    module_path: pam_unix.so
    new_type: auth
    new_control: required
    new_module_path: pam_faillock.so
    module_arguments: 'preauth
        silent
        deny={{ var_accounts_passwords_pam_faillock_deny }}'
    state: before
  loop:
    - system-auth
    - password-auth
  tags:
    - cat II

- name: "DISA RHEL-07-010320: Add deny argument to auth pam_faillock preauth"
  pamd:
    name: "{{ item }}"
    type: auth
    control: required
    module_path: pam_faillock.so
    module_arguments: 'preauth
        silent
        deny={{ var_accounts_passwords_pam_faillock_deny }}'
    state: args_present
  loop:
    - system-auth
    - password-auth
  tags:
    - cat II

- name: "DISA RHEL-07-010320: Add auth pam_faillock authfail deny after pam_unix.so"
  pamd:
    name: "{{ item }}"
    type: auth
    control: sufficient
    module_path: pam_unix.so
    new_type: auth
    new_control: '[default=die]'
    new_module_path: pam_faillock.so
    module_arguments: 'authfail
        deny={{ var_accounts_passwords_pam_faillock_deny }}'
    state: after
  loop:
    - system-auth
    - password-auth
  tags:
    - cat II

- name: "DISA RHEL-07-010320: Add deny argument to auth pam_faillock authfail"
  pamd:
    name: "{{ item }}"
    type: auth
    new_type: auth
    control: '[default=die]'
    module_path: pam_faillock.so
    module_arguments: 'authfail
        deny={{ var_accounts_passwords_pam_faillock_deny }}'
    state: args_present
  loop:
    - system-auth
    - password-auth
  tags:
    - cat II

- name: "DISA RHEL-07-010320: Add account pam_faillock before pam_unix.so"
  pamd:
    name: "{{ item }}"
    type: account
    control: required
    module_path: pam_unix.so
    new_type: account
    new_control: required
    new_module_path: pam_faillock.so
    state: before
  loop:
    - system-auth
    - password-auth
  tags:
    - cat II
...