---
- name: "DISA-STIG-RHEL-07-040830: Ensure sysctl net.ipv6.conf.all.accept_source_route is set"
  sysctl:
    name: net.ipv6.conf.all.accept_source_route
    value: "{{ sysctl_net_ipv6_conf_all_accept_source_route_value }}"
    state: present
    reload: yes
  tags:
    - cat II
...
