---
- name: "DISA-STIG-RHEL-07-040660: Ensure sysctl net.ipv4.conf.all.send_redirects is set to 0"
  sysctl:
    name: net.ipv4.conf.all.send_redirects
    value: 0
    state: present
    reload: yes
  tags:
    - cat II
...
