---
- name: "DISA-STIG-RHEL-07-040380: Disable SSH Support for User Known Hosts"
  lineinfile:
    create: yes
    dest: /etc/ssh/sshd_config
    regexp: ^IgnoreUserKnownHosts
    line: IgnoreUserKnownHosts yes
    insertbefore: ^Match
    firstmatch: yes
    validate: /usr/sbin/sshd -t -f %s
  #notify: restart sshd
  tags:
    - cat II
...
