---
- name: "DISA RHEL-07-030560: Search /etc/audit/rules.d for audit rule semanage entries"
  find:
    paths: "/etc/audit/rules.d"
    recurse: no
    contains: "^.*path=/usr/sbin/semanage.*$"
    patterns: "*.rules"
  register: find_semanage
  tags:
    - cat II

- name: "DISA RHEL-07-030560: Use /etc/audit/rules.d/privileged.rules as the recipient for the rule"
  set_fact:
    all_files:
      - /etc/audit/rules.d/privileged.rules
  tags:
    - cat II

- name: "DISA RHEL-07-030560: Use matched file as the recipient for the rule"
  set_fact:
    all_files:
      - "{{ find_semanage.files | map(attribute='path') | list | first }}"
    when: find_semanage.matched > 0 and True
    tags:
      - cat II

- name: "DISA RHEL-07-030560: Inserts/replaces the semanage rule in rules.d"
  lineinfile:
    path: "{{ all_files[0] }}"
    line: '-a always,exit -F path=/usr/sbin/semanage -F perm=x -F auid>=1000 -F auid!=unset -F key=privileged'
    create: yes
  tags:
    - cat II

- name: "DISA RHEL-07-030560: Inserts/replaces the semanage rule in audit.rules"
  lineinfile:
    path: /etc/audit/audit.rules
    line: '-a always,exit -F path=/usr/sbin/semanage -F perm=x -F auid>=1000 -F auid!=unset -F key=privileged'
    create: yes
  tags:
    - cat II
...
