---
- name: "DISA-STIG-RHEL-07-040630: Ensure sysctl net.ipv4.icmp_echo_ignore_broadcasts is set"
  sysctl:
    name: net.ipv4.icmp_echo_ignore_broadcasts
    value: "{{ sysctl_net_ipv4_icmp_echo_ignore_broadcasts_value }}"
    state: present
    reload: yes
  tags:
    - cat II
...
