---
- name: "DISA RHEL-07-030870: Set architecture for audit passwd tasks"
  set_fact:
    audit_arch: "b{{ ansible_architecture | regex_replace('.*(\\d\\d$)','\\1') }}"
  tags:
    - cat II

- name: "DISA RHEL-07-030870: Search /etc/audit/rules.d for other user/group modification audit rules"
  find:
    paths: "/etc/audit/rules.d"
    recurse: no
    contains: "-k audit_rules_usergroup_modification$"
    patterns: "*.rules"
  register: find_passwd
  tags:
    - cat II

- name: "DISA RHEL-07-030870: If existing user/group modification ruleset not found, use /etc/audit/rules.d/privileged.rules as the recipient for the rule"
  set_fact:
    all_files:
      - /etc/audit/rules.d/privileged.rules
  tags:
    - cat II

- name: "DISA RHEL-07-030870: Use matched file as the recipient for the rule"
  set_fact:
    all_files:
      - "{{ find_passwd.files | map(attribute='path') | list | first }}"
  when: find_passwd.matched > 0
  tags:
    - cat II

- name: "DISA RHEL-07-030870: Inserts/replaces the passwd rule in rules.d when on x86"
  lineinfile:
    path: "{{ all_files[0] }}"
    line: "-w /etc/passwd -p wa -k audit_rules_usergroup_modification"
    create: yes
  tags:
    - cat II

- name: "DISA RHEL-07-030870: Inserts/replaces the passwd rule in /etc/audit/audit.rules"
  lineinfile:
    line: "-w /etc/passwd -p wa -k audit_rules_usergroup_modification"
    state: present
    dest: /etc/audit/audit.rules
  tags:
    - cat II
...
