---
- name: "DISA RHEL-07-030640: Search /etc/audit/rules.d for unix_chkpwd audit rule entries"
  find:
    paths: "/etc/audit/rules.d"
    recurse: no
    contains: "^.*path=/usr/sbin/unix_chkpwd.*$"
    patterns: "*.rules"
  register: find_unix_chkpwd
  tags:
    - cat II

- name: "DISA RHEL-07-030640: Use /etc/audit/rules.d/privileged.rules as the recipient for the rule"
  set_fact:
    all_files:
      - /etc/audit/rules.d/privileged.rules
  when: find_unix_chkpwd.matched == 0 and True
  tags:
    - cat II

- name: "DISA RHEL-07-030640: Use matched file as the recipient for the rule"
  set_fact:
    all_files:
      - "{{ find_unix_chkpwd.files | map(attribute='path') | list | first }}"
  when: find_unix_chkpwd.matched > 0 and True
  tags:
    - cat II

- name: "DISA RHEL-07-030640: Inserts/replaces the unix_chkpwd rule in rules.d"
  lineinfile:
    path: "{{ all_files[0] }}"
    line: "-a always,exit -F path=/usr/sbin/unix_chkpwd -F perm=x -F auid>=1000 -F auid!=unset -F key=privileged"
    create: yes
  tags:
    - cat II

- name: "DISA RHEL-07-030640: Inserts/replaces the unix_chkpwd rule in /etc/audit/audit.rules"
  lineinfile:
    path: /etc/audit/audit.rules
    line: "-a always,exit -F path=/usr/sbin/unix_chkpwd -F perm=x -F auid>=1000 -F auid!=unset -F key=privileged"
    create: yes
  tags:
    - cat II
...   