---
    - package_facts:
        manager: auto
      name: "DISA-STIG-RHEL-07-040000: Gather the package facts"
      tags:
        - cat III

    - name: "DISA-STIG-RHEL-07-040000: Find /etc/security/limits.d files containing maxlogins configuration"
      find:
        paths: /etc/security/limits.d
        contains: ^[\s]*\*[\s]+(?:(?:hard)|(?:-))[\s]+maxlogins
        patterns: '*.conf'
      register: maxlogins
      when: '"pam" in ansible_facts.packages'
      tags:
        - cat III

    - name: "DISA-STIG-RHEL-07-040000: Limit the Number of Concurrent Login Sessions Allowed Per User in files from limits.d"
      replace:
        dest: '{{ item.path }}'
        regexp: ^#?\*.*maxlogins.*
        replace: '*          hard    maxlogins     {{ var_accounts_max_concurrent_login_sessions }}'
      with_items:
        - '{{ maxlogins.files }}'
      when: '"pam" in ansible_facts.packages'
      tags:
        - cat III

    - name: "DISA-STIG-RHEL-07-040000: Limit the Number of Concurrent Login Sessions Allowed Per User"
      lineinfile:
        state: present
        dest: /etc/security/limits.conf
        insertbefore: ^# End of file
        regexp: ^#?\*.*maxlogins
        line: '*          hard    maxlogins     {{ var_accounts_max_concurrent_login_sessions }}'
        create: true
      when:
        - maxlogins.matched == 0
        - '"pam" in ansible_facts.packages'
      tags:
        - cat III
...
