---
- name: "DISA RHEL-07-030570: Search /etc/audit/rules.d for audit rule setsebool entries"
  find:
    paths: "/etc/audit/rules.d"
    recurse: no
    contains: "^.*path=/usr/sbin/setsebool.*$"
    patterns: "*.rules"
  register: find_setsebool
  tags:
    - cat II

- name: "DISA RHEL-07-030570: Use /etc/audit/rules.d/privileged.rules as the recipient for the rule"
  set_fact:
    all_files:
      - /etc/audit/rules.d/privileged.rules
  tags:
    - cat II

- name: "DISA RHEL-07-030570: Use matched file as the recipient for the rule"
  set_fact:
    all_files:
      - "{{ find_setsebool.files | map(attribute='path') | list | first }}"
  when: find_setsebool.matched > 0 and True
  tags:
    - cat II

- name: "DISA RHEL-07-030570: Inserts/replaces the setsebool rule in rules.d"
  lineinfile:
    path: "{{ all_files[0] }}"
    line: '-a always,exit -F path=/usr/sbin/setsebool -F perm=x -F auid>=1000 -F auid!=unset -F key=privileged'
    create: yes
  tags:
    - cat II

- name: "DISA RHEL-07-030570: Inserts/replaces the setsebool rule in audit.rules"
  lineinfile:
    path: /etc/audit/audit.rules
    line: '-a always,exit -F path=/usr/sbin/setsebool -F perm=x -F auid>=1000 -F auid!=unset -F key=privileged'
    create: yes
  tags:
    - cat II
...
