---
- name: "DISA RHEL-07-020240: Ensure the Default UMASK is Set Correctly"
  lineinfile:
    create: yes
    dest: /etc/login.defs
    regexp: ^UMASK
    line: "UMASK {{ var_accounts_user_umask }}"
  tags:
    - cat II
...