---
- name: "DISA RHEL-07-010030: Enable GNOME3 Login Warning Banner"
  copy:
    src: /nfs/admin/twr_files/work/dconf/00-security-settings
    dest: /etc/dconf/db/gdm.d/00-security-settings
    owner: root
    group: root
    mode: 0644
  when: gui_present
  notify:
    - update dconf
  tags:
    - cat II

- name: "DISA RHEL-07-010030: Prevent user modification of GNOME banner-message-enabled"
  lineinfile:
    path: /etc/dconf/db/local.d/locks/00-security-settings-lock
    regexp: '^/org/gnome/login-screen/banner-message-enable'
    line: '/org/gnome/login-screen/banner-message-enable'
    create: yes
  when: gui_present
  notify:
    - update dconf
  tags:
    - cat II
...