---
- name: "DISA RHEL-07-030760: Search /etc/audit/rules.d for postdrop audit rule entries"
  find:
    paths: "/etc/audit/rules.d"
    recurse: no
    contains: "^.*path=/usr/sbin/postdrop.*$"
    patterns: "*.rules"
  register: find_postdrop
  tags:
    - cat II

- name: "DISA RHEL-07-030760: Use /etc/audit/rules.d/privileged.rules as the recipient for the rule"
  set_fact:
    all_files:
      - /etc/audit/rules.d/privileged.rules
  when: find_postdrop.matched == 0 and True
  tags:
    - cat II

- name: "DISA RHEL-07-030760: Use matched file as the recipient for the rule"
  set_fact:
    all_files:
      - "{{ find_postdrop.files | map(attribute='path') | list | first }}"
  when: find_postdrop.matched > 0 and True
  tags:
    - cat II

- name: "DISA RHEL-07-030760: Inserts/replaces the postdrop rule in rules.d"
  lineinfile:
    path: "{{ all_files[0] }}"
    line: "-a always,exit -F path=/usr/sbin/postdrop -F perm=x -F auid>=1000 -F auid!=unset -F key=privileged"
    create: yes
  tags:
    - cat II

- name: "DISA RHEL-07-030760: Inserts/replaces the postdrop rule in /etc/audit/audit.rules"
  lineinfile:
    path: /etc/audit/audit.rules
    line: "-a always,exit -F path=/usr/sbin/postdrop -F perm=x -F auid>=1000 -F auid!=unset -F key=privileged"
    create: yes
  tags:
    - cat II
...   