---
- name: "DISA RHEL-07-030670: Search /etc/audit/rules.d for userhelper audit rule entries"
  find:
    paths: "/etc/audit/rules.d"
    recurse: no
    contains: "^.*path=/usr/sbin/userhelper.*$"
    patterns: "*.rules"
  register: find_userhelper
  tags:
    - cat II

- name: "DISA RHEL-07-030670: Use /etc/audit/rules.d/privileged.rules as the recipient for the rule"
  set_fact:
    all_files:
      - /etc/audit/rules.d/privileged.rules
  when: find_userhelper.matched == 0 and True
  tags:
    - cat II

- name: "DISA RHEL-07-030670: Use matched file as the recipient for the rule"
  set_fact:
    all_files:
      - "{{ find_userhelper.files | map(attribute='path') | list | first }}"
  when: find_userhelper.matched > 0 and True
  tags:
    - cat II

- name: "DISA RHEL-07-030670: Inserts/replaces the userhelper rule in rules.d"
  lineinfile:
    path: "{{ all_files[0] }}"
    line: "-a always,exit -F path=/usr/sbin/userhelper -F perm=x -F auid>=1000 -F auid!=unset -F key=privileged"
    create: yes
  tags:
    - cat II

- name: "DISA RHEL-07-030670: Inserts/replaces the userhelper rule in /etc/audit/audit.rules"
  lineinfile:
    path: /etc/audit/audit.rules
    line: "-a always,exit -F path=/usr/sbin/userhelper -F perm=x -F auid>=1000 -F auid!=unset -F key=privileged"
    create: yes
  tags:
    - cat II
...   