---
- name: "DISA RHEL-07-030800: Search /etc/audit/rules.d for crontab audit rule entries"
  find:
    paths: "/etc/audit/rules.d"
    recurse: no
    contains: "^.*path=/usr/bin/crontab.*$"
    patterns: "*.rules"
  register: find_crontab
  tags:
    - cat II

- name: "DISA RHEL-07-030800: Use /etc/audit/rules.d/privileged.rules as the recipient for the rule"
  set_fact:
    all_files:
      - /etc/audit/rules.d/privileged.rules
  when: find_crontab.matched == 0 and True
  tags:
    - cat II

- name: "DISA RHEL-07-030800: Use matched file as the recipient for the rule"
  set_fact:
    all_files:
      - "{{ find_crontab.files | map(attribute='path') | list | first }}"
  when: find_crontab.matched > 0 and True
  tags:
    - cat II

- name: "DISA RHEL-07-030800: Inserts/replaces the crontab rule in rules.d"
  lineinfile:
    path: "{{ all_files[0] }}"
    line: "-a always,exit -F path=/usr/bin/crontab -F perm=x -F auid>=1000 -F auid!=unset -F key=privileged"
    create: yes
  tags:
    - cat II

- name: "DISA RHEL-07-030800: Inserts/replaces the crontab rule in /etc/audit/audit.rules"
  lineinfile:
    path: /etc/audit/audit.rules
    line: "-a always,exit -F path=/usr/bin/crontab -F perm=x -F auid>=1000 -F auid!=unset -F key=privileged"
    create: yes
  tags:
    - cat II
...   