---
- name: "DISA RHEL-07-021000: Look up device associated to mountpoint"
  shell: mount | grep ' /home ' |cut -d ' ' -f 1
  args:
    warn: False # Ignore ANSIBLE0006, we can't fetch device name with mount module
  register: device_name
  check_mode: no
  changed_when: False
  tags:
    - cat II

- block:
  - name: "DISA RHEL-07-021000: Look up device previous mount option"
    shell: mount | grep ' /home ' | sed -re 's:.*\((.*)\):\1:'
    args:
      warn: False # Ignore ANSIBLE0006, we can't fetch current mount options with mount module
    register: device_cur_mountoption
    check_mode: no

  - name: "DISA RHEL-07-021000: Look up device fstype"
    shell: mount | grep ' /home ' | cut -d ' ' -f 5
    args:
      warn: False # Ignore ANSIBLE0006, we can't fetch fstype with mount module
    register: device_fstype
    check_mode: no

  - name: "DISA RHEL-07-021000: Ensure permission nosuid are set on /home"
    mount:
      path: "/home"
      src: "{{ device_name.stdout }}"
      opts: "{{ device_cur_mountoption.stdout }},nosuid"
      state: "mounted"
      fstype: "{{ device_fstype.stdout }}"
  when: device_name.stdout | length > 0
  tags:
    - cat II
...