---
- name: "DISA RHEL-07-030650: Search /etc/audit/rules.d for gpasswd audit rule entries"
  find:
    paths: "/etc/audit/rules.d"
    recurse: no
    contains: "^.*path=/usr/bin/gpasswd.*$"
    patterns: "*.rules"
  register: find_gpasswd
  tags:
    - cat II

- name: "DISA RHEL-07-030650: Use /etc/audit/rules.d/privileged.rules as the recipient for the rule"
  set_fact:
    all_files:
      - /etc/audit/rules.d/privileged.rules
  when: find_gpasswd.matched == 0 and True
  tags:
    - cat II

- name: "DISA RHEL-07-030650: Use matched file as the recipient for the rule"
  set_fact:
    all_files:
      - "{{ find_gpasswd.files | map(attribute='path') | list | first }}"
  when: find_gpasswd.matched > 0 and True
  tags:
    - cat II

- name: "DISA RHEL-07-030650: Inserts/replaces the gpasswd rule in rules.d"
  lineinfile:
    path: "{{ all_files[0] }}"
    line: "-a always,exit -F path=/usr/bin/gpasswd -F perm=x -F auid>=1000 -F auid!=unset -F key=privileged"
    create: yes
  tags:
    - cat II

- name: "DISA RHEL-07-030650: Inserts/replaces the gpasswd rule in /etc/audit/audit.rules"
  lineinfile:
    path: /etc/audit/audit.rules
    line: "-a always,exit -F path=/usr/bin/gpasswd -F perm=x -F auid>=1000 -F auid!=unset -F key=privileged"
    create: yes
  tags:
    - cat II
...   