---
- name: "DISA-STIG-RHEL-07-040641: Ensure sysctl net.ipv4.conf.all.accept_redirects is set"
  sysctl:
    name: net.ipv4.conf.all.accept_redirects
    value: "{{ sysctl_net_ipv4_conf_all_accept_redirects_value }}"
    state: present
    reload: yes
  tags:
    - cat II
...
