---
    - name: "DISA-STIG-RHEL-07-010061: Enable the GNOME3 Login Smartcard Authentication"
      ini_file:
        dest: /etc/dconf/db/gdm.d/00-security-settings
        section: org/gnome/login-screen
        option: enable-smartcard-authentication
        value: "true"
        create: yes
      tags:
        - cat II

    - name: "DISA-STIG-RHEL-07-010061: Prevent user modification of GNOME3 disablement of Smartcard Authentication"
      lineinfile:
        path: /etc/dconf/db/gdm.d/locks/00-security-settings-lock
        regexp: '^/org/gnome/login-screen/enable-smartcard-authentication'
        line: '/org/gnome/login-screen/enable-smartcard-authentication'
        create: yes
      tags:
        - cat II
...
