---
- name: "DISA RHEL-07-010290: Prevent Log In to Accounts With Empty Password - system-auth"
  replace:
    path: /etc/pam.d/system-auth
    regexp: 'nullok'
  tags:
    - cat I

- name: "DISA RHEL-07-010290: Prevent Log In to Accounts With Empty Password - password-auth"
  replace:
    path: /etc/pam.d/password-auth
    regexp: 'nullok'
  tags:
    - cat I
...