---
- name: "DISA RHEL-07-030550: Set architecture for audit ftruncate tasks"
  set_fact:
    audit_arch: "b{{ ansible_architecture | regex_replace('.*(\\d\\d$)','\\1') }}"
  tags:
    - cat II

- name: "DISA RHEL-07-030550: Search /etc/audit/rules.d for other DAC audit rules"
  find:
    paths: "/etc/audit/rules.d"
    recurse: no
    contains: "-F key=perm_mod$"
    patterns: "*.rules"
  register: find_ftruncate
  tags:
    - cat II

- name: "DISA RHEL-07-030550: If existing DAC ruleset not found, use /etc/audit/rules.d/access.rules as the recipient for the rule"
  set_fact:
    all_files:
      - /etc/audit/rules.d/access.rules
  when: find_ftruncate.matched == 0 and True
  tags:
    - cat II

- name: "DISA RHEL-07-030550: Use matched file as the recipient for the rule"
  set_fact:
    all_files:
      - "{{ find_ftruncate.files | map(attribute='path') | list | first }}"
  when: find_ftruncate.matched > 0 and True
  tags:
    - cat II

- name: "DISA RHEL-07-030550: Inserts/replaces the ftruncate rule in rules.d when on x86"
  lineinfile:
    path: "{{ all_files[0] }}"
    line: "{{ item }}"
    create: yes
  with_items:
    - "-a always,exit -F arch=b32 -S ftruncate -F exit=-EACCES -F auid>=1000 -F auid!=unset -F key=access"
    - "-a always,exit -F arch=b32 -S ftruncate -F exit=-EPERM -F auid>=1000 -F auid!=unset -F key=access"
  tags:
    - cat II

- name: "DISA RHEL-07-030550: Inserts/replaces the ftruncate rule in rules.d when on x86_64"
  lineinfile:
    path: "{{ all_files[0] }}"
    line: "{{ item }}"
    create: yes
  with_items:
    - "-a always,exit -F arch=b64 -S ftruncate -F exit=-EACCES -F auid>=1000 -F auid!=unset -F key=access"
    - "-a always,exit -F arch=b64 -S ftruncate -F exit=-EPERM -F auid>=1000 -F auid!=unset -F key=access"
  when: audit_arch == 'b64' and True
  tags:
    - cat II

- name: "DISA RHEL-07-030550: Inserts/replaces the ftruncate rule in /etc/audit/audit.rules when on x86"
  lineinfile:
    line: "{{ item }}"
    state: present
    dest: /etc/audit/audit.rules
  with_items:
    - "-a always,exit -F arch=b32 -S ftruncate -F exit=-EACCES -F auid>=1000 -F auid!=unset -F key=access"
    - "-a always,exit -F arch=b32 -S ftruncate -F exit=-EPERM -F auid>=1000 -F auid!=unset -F key=access"
  tags:
    - cat II

- name: "DISA RHEL-07-030550: Inserts/replaces the ftruncate rule in audit.rules when on x86_64"
  lineinfile:
    line: "{{ item }}"
    state: present
    dest: /etc/audit/audit.rules
    create: yes
  with_items:
    - "-a always,exit -F arch=b64 -S ftruncate -F exit=-EACCES -F auid>=1000 -F auid!=unset -F key=access"
    - "-a always,exit -F arch=b64 -S ftruncate -F exit=-EPERM -F auid>=1000 -F auid!=unset -F key=access"
  when: audit_arch == 'b64' and True
  tags:
    - cat II
...   