---
- name: "DISA-STIG-RHEL-07-040610: Ensure sysctl net.ipv4.conf.all.accept_source_route is set"
  sysctl:
    name: net.ipv4.conf.all.accept_source_route
    value: "{{ sysctl_net_ipv4_conf_all_accept_source_route_value }}"
    state: present
    reload: yes
  tags:
    - cat II
...
