---
- name: "DISA RHEL-07-020050: Ensure GPG check is globally activated (yum)"
  ini_file:
    dest: /etc/yum.conf
    section: main
    option: gpgcheck
    value: 1
    create: False
  when: (ansible_facts.lsb.id == "RedHatEnterpriseServer" or ansible_facts.lsb.id == "RedHatEnterpriseWorkstation") and True
  tags:
    - cat I
...