---
- name: "DISA RHEL-07-010040: Set the GNOME3 Login Warning Banner Text (1/4)"
  file:
    path: "/etc/dconf/db/{{ item }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items:
    - gdm.d
    - gdm.d/locks
  when: gui_present
  tags:
    - cat II

- name: "DISA RHEL-07-010040: Set the GNOME3 Login Warning Banner Text (2/4)"
  file:
    path: "/etc/dconf/db/gdm.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
    state: touch
  with_items:
    - 00-security-settings
    - locks/00-security-settings-lock
  when: gui_present
  tags:
  - cat II

- name: "DISA RHEL-07-010040: Set the GNOME3 Login Warning Banner Text (3/4)"
  ini_file:
    dest: /etc/dconf/db/gdm.d/00-security-settings
    section: org/gnome/login-screen
    option: banner-message-text
    value: string '{{ login_banner_text }}'
    create: yes
    when: gui_present
  tags:
    - cat II

- name: "DISA RHEL-07-010040: Set the GNOME3 Login Warning Banner Text (4/4)"
  lineinfile:
    path: '/etc/dconf/db/gdm.d/locks/00-security-settings-lock'
    regexp: '^org/gnome/login-screen/banner-message-text$'
    line: 'org/gnome/login-screen/banner-message-text'
    create: yes
    state: present
    when: gui_present
  tags:
    - cat II
...