---
- name: "DISA RHEL-07-030630: Search /etc/audit/rules.d for passwd audit rule entries"
  find:
    paths: "/etc/audit/rules.d"
    recurse: no
    contains: "^.*path=/usr/bin/passwd.*$"
    patterns: "*.rules"
  register: find_passwd
  tags:
    - cat II

- name: "DISA RHEL-07-030630: Use /etc/audit/rules.d/privileged.rules as the recipient for the rule"
  set_fact:
    all_files:
      - /etc/audit/rules.d/privileged.rules
  when: find_passwd.matched == 0 and True
  tags:
    - cat II

- name: "DISA RHEL-07-030630: Use matched file as the recipient for the rule"
  set_fact:
    all_files:
      - "{{ find_passwd.files | map(attribute='path') | list | first }}"
  when: find_passwd.matched > 0 and True
  tags:
    - cat II

- name: "DISA RHEL-07-030630: Inserts/replaces the passwd rule in rules.d"
  lineinfile:
    path: "{{ all_files[0] }}"
    line: "-a always,exit -F path=/usr/bin/passwd -F perm=x -F auid>=1000 -F auid!=unset -F key=privileged"
    create: yes
  tags:
    - cat II

- name: "DISA RHEL-07-030630: Inserts/replaces the passwd rule in /etc/audit/audit.rules"
  lineinfile:
    path: /etc/audit/audit.rules
    line: "-a always,exit -F path=/usr/bin/passwd -F perm=x -F auid>=1000 -F auid!=unset -F key=privileged"
    create: yes
  tags:
    - cat II
...   