---
- name: "DISA-STIG-RHEL-07-040400: Use Only Approved MACs"
  lineinfile:
    create: yes
    dest: /etc/ssh/sshd_config
    regexp: ^MACs
    line: "MACs {{ sshd_approved_macs }}"
    validate: /usr/sbin/sshd -t -f %s
  #notify: restart sshd
  tags:
    - cat II
...
