---
- name: "DISA RHEL-07-030872: Set architecture for audit gshadow tasks"
  set_fact:
    audit_arch: "b{{ ansible_architecture | regex_replace('.*(\\d\\d$)','\\1') }}"
  tags:
    - cat II

- name: "DISA RHEL-07-030872: Search /etc/audit/rules.d for other user/group modification audit rules"
  find:
    paths: "/etc/audit/rules.d"
    recurse: no
    contains: "-k audit_rules_usergroup_modification$"
    patterns: "*.rules"
  register: find_gshadow
  tags:
    - cat II

- name: "DISA RHEL-07-030872: If existing user/group modification ruleset not found, use /etc/audit/rules.d/privileged.rules as the recipient for the rule"
  set_fact:
    all_files:
      - /etc/audit/rules.d/privileged.rules
  tags:
    - cat II

- name: "DISA RHEL-07-030872: Use matched file as the recipient for the rule"
  set_fact:
    all_files:
      - "{{ find_gshadow.files | map(attribute='path') | list | first }}"
  tags:
    - cat II

- name: "DISA RHEL-07-030872: Inserts/replaces the gshadow rule in rules.d when on x86"
  lineinfile:
    path: "{{ all_files[0] }}"
    line: "-w /etc/gshadow -p wa -k audit_rules_usergroup_modification"
    create: yes
  tags:
    - cat II

- name: "DISA RHEL-07-030872: Inserts/replaces the gshadow rule in /etc/audit/audit.rules"
  lineinfile:
    line: "-w /etc/gshadow -p wa -k audit_rules_usergroup_modification"
    state: present
    dest: /etc/audit/audit.rules
  tags:
    - cat II
...
