---
- name: "DISA-STIG-RHEL-07-040470: Disable Compression or Set Compression to delayed"
  lineinfile:
    create: yes
    dest: /etc/ssh/sshd_config
    regexp: (?i)^#?compression
    line: Compression delayed
    validate: /usr/sbin/sshd -t -f %s
  #notify: restart sshd
  tags:
    - cat II
...
