---
- name: "DISA RHEL-07-020260: Security patches are up to date (random values for time)"
  set_fact:
    update_minute: "{{ 59 | random }}"
    update_hour: "{{ 5 | random }}"
    cacheable: yes
  run_once: yes
  tags:
    - cat II

- name: "DISA RHEL-07-020260: Security patches are up to date (cron entry)"
  cron:
    name: Daily update
    hour: "{{ update_hour|int }}"
    minute: "{{ update_minute|int }}"
    job: /usr/bin/yum --exclude=kernel* -y update > /dev/null 2>&1
  tags:
    - cat II
...