---
- name: "DISA RHEL-07-010310: Set Account Expiration Following Inactivity"
  lineinfile:
    create: yes
    path: /etc/default/useradd
    regexp: ^INACTIVE
    line: "INACTIVE={{ var_account_disable_post_pw_expiration }}"
  tags:
    - cat II
...