---
- name: "DISA-STIG-RHEL-07-030300: Make sure that a remote server is configured for Audispd"
  lineinfile:
    path: /etc/audisp/audisp-remote.conf
    line: remote_server = {{ var_audispd_remote_server }}
    regexp: ^\s*remote_server\s*=.*$
    create: true
    state: present
  tags:
    - cat II
...
