---
- name: "DISA RHEL-07-010180: PAM Encrypt passwords with SHA512"
  lineinfile:
    path: "/etc/pam.d/{{ item.path }}"
    regexp: '^password\s*sufficient\s*pam_unix\.so.*$'
    line: "password     sufficient     pam_unix.so sha512 shadow try_first_pass use_authtok"
    insertafter: "{{ item.insertafter }}"
  with_items:
    - { path: "system-auth", insertafter: '^password\s*requisite\s*pam_pwquality\.so.*' }
    - { path: "password-auth", insertafter: '^password\s*requisite\s*pam_pwquality\.so.*' }
  tags:
    - cat II
...