---
- name: "DISA RHEL-07-010491: Disable Ctrl-Alt-Del in Gnome GUI"
  copy:
    src: /nfs/admin/twr_files/work/dconf/00-disable-CAD
    dest: /etc/dconf/db/local.d/00-disable-CAD
    owner: root
    group: root
    mode: 0644
  when: gui_present
  notify:
    - update dconf
  tags:
    - cat I
...