---
- name: "DISA-STIG-RHEL-07-040440: Disable Kerberos Authentication"
  lineinfile:
    create: yes
    dest: /etc/ssh/sshd_config
    regexp: (?i)^#?kerberosauthentication
    line: KerberosAuthentication no
    validate: /usr/sbin/sshd -t -f %s
  #notify: restart sshd
  tags:
    - cat II
...
