---
- name: "DISA-STIG-RHEL-07-040430: Disable GSSAPI Authentication"
  lineinfile:
    create: yes
    dest: /etc/ssh/sshd_config
    regexp: (?i)^#?gssapiauthentication
    line: GSSAPIAuthentication no
    validate: /usr/sbin/sshd -t -f %s
  #notify: sshd -t -f %s
  tags:
    - cat II
...
