---
- name: "DISA RHEL-07-030310: Configure Kerberos 5 Encryption in Audit Event Multiplexor (audispd)"
  lineinfile:
    dest: /etc/audisp/audisp-remote.conf
    line: enable_krb5 = yes
    regexp: ^\s*enable_krb5\s*=\s*.*$
    state: present
    create: true
  tags:
    - cat II
...