---
- name: "DISA RHEL-07-040390: Allow Only SSH Protocol 2"
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^Protocol [0-9]"
    line: "Protocol 2"
    validate: /usr/sbin/sshd -t -f %s
  tags:
    - cat I
...