---
- name: "DISA STIG-RH-7-010020: Read files with incorrect hash"
  shell: "rpm -Va | grep -E '^..5.* /(bin|sbin|lib|lib64|usr)/' | awk '{print $NF}'"
  args:
    warn: False # Ignore ANSIBLE0006, we can't fetch files with incorrect hash using rpm module
  register: files_with_incorrect_hash
  changed_when: False
  check_mode: no

- name: "DISA STIG-RH-7-010020: Reinstall packages of files with incorrect hash"
  shell: "yum reinstall $(rpm -qf '{{ item }}')"
  args:
    warn: False # Ignore ANSIBLE0006, this task is flexible with regards to package manager
  with_items: "{{ files_with_incorrect_hash.stdout_lines }}"
  when: (package_manager_reinstall_cmd is defined and (files_with_incorrect_hash.stdout_lines | length > 0)) and True
...