---
    - name: "DISA-STIG-RHEL-07-030819: Set architecture for audit create_module tasks"
      set_fact:
        audit_arch: "b{{ ansible_architecture | regex_replace('.*(\\d\\d$)','\\1') }}"
      tags:
        - cat II
    
    # Inserts/replaces the rule in /etc/audit/rules.d
    
    - name: "DISA-STIG-RHEL-07-030819: Search /etc/audit/rules.d for audit rule entries"
      find:
        paths: /etc/audit/rules.d
        recurse: false
        contains: ^.*create_module.*$
        patterns: '*.rules'
      register: find_create_module
      tags:
        - cat II

    - name: "DISA-STIG-RHEL-07-030819: Use /etc/audit/rules.d/privileged.rules as the recipient for the rule"
      set_fact:
        all_files:
        - /etc/audit/rules.d/privileged.rules
      when: find_create_module.matched == 0 and (ansible_virtualization_role != "guest" or ansible_virtualization_type != "docker")
      tags:
        - cat II

    - name: "DISA-STIG-RHEL-07-030819: Use matched file as the recipient for the rule"
      set_fact:
        all_files:
        - '{{ find_create_module.files | map(attribute=''path'') | list | first }}'
      when: find_create_module.matched > 0 and (ansible_virtualization_role != "guest" or ansible_virtualization_type != "docker")
      tags:
        - cat II

    - name: "DISA-STIG-RHEL-07-030819: Inserts/replaces the create_module rule in rules.d"
      lineinfile:
        path: '{{ all_files[0] }}'
        line: '-a always,exit -F arch=b32 -S create_module -k module-change'
        state: present
        create: true
      tags:
        - cat II
      when:  # Bare-metal/VM task, not applicable for containers
        - (ansible_virtualization_role != "guest" or ansible_virtualization_type != "docker")

    - name: "DISA-STIG-RHEL-07-030819: Inserts/replaces the create_module rule in rules.d on x86_64"
      lineinfile:
        path: '{{ all_files[0] }}'
        line: '-a always,exit -F arch=b64 -S create_module -k module-change'
        state: present
        create: true
      when: audit_arch == 'b64' and (ansible_virtualization_role != "guest" or ansible_virtualization_type != "docker")
      tags:
        - cat II
    
    # Inserts/replaces the create_modules rule in /etc/audit/audit.rules
    
    - name: "DISA-STIG-RHEL-07-030819: Inserts/replaces the create_module rule in audit.rules"
      lineinfile:
        path: /etc/audit/audit.rules
        line: '-a always,exit -F arch=b32 -S create_module -k module-change'
        create: true
      tags:
        - cat II
      when:  # Bare-metal/VM task, not applicable for containers
        - (ansible_virtualization_role != "guest" or ansible_virtualization_type != "docker")

    - name: "DISA-STIG-RHEL-07-030819: Inserts/replaces the create_module rule in audit.rules when on x86_64"
      lineinfile:
        path: /etc/audit/audit.rules
        line: '-a always,exit -F arch=b64 -S create_module -k module-change'
        create: true
      when: audit_arch == 'b64' and (ansible_virtualization_role != "guest" or ansible_virtualization_type != "docker")
      tags:
        - cat II
... 
