---
- name: "Enable GNOME3 Login Warning Banner"
  ini_file:
    dest: "/etc/dconf/db/local.d/00-security-settings"
    section: "org/gnome/login-screen"
    option: banner-message-enable
    value: "true"
    create: yes
  when: gui_present

- name: "Prevent user modification of GNOME banner-message-enabled"
  lineinfile:
    path: /etc/dconf/db/local.d/locks/00-security-settings-lock
    regexp: '^/org/gnome/login-screen/banner-message-enable'
    line: '/org/gnome/login-screen/banner-message-enable'
    create: yes
  when: gui_present
...