---
- name: "DISA-STIG-RHEL-07-040620: Ensure sysctl net.ipv4.conf.default.accept_source_route is set"
  sysctl:
    name: net.ipv4.conf.default.accept_source_route
    value: "{{ sysctl_net_ipv4_conf_default_accept_source_route_value }}"
    state: present
    reload: yes
  tags:
    - cat II
...
