---
- package_facts:
    manager: auto
  name: Gather the package facts
  tags:
    - cat II

- name: "DISA-STIG-RHEL-07-010119: Set Password Retry Prompts Permitted Per-Session - system-auth (change)"
  replace:
    dest: /etc/pam.d/system-auth
    regexp: (^.*\spam_pwquality.so\s.*retry\s*=\s*)(\S+)(.*$)
    replace: \g<1>{{ var_password_pam_retry }}\g<3>
  when: '"pam" in ansible_facts.packages'
  tags:
    - cat II

- name: "DISA-STIG-RHEL-07-010119: Set Password Retry Prompts Permitted Per-Session - system-auth (add)"
  replace:
    dest: /etc/pam.d/system-auth
    regexp: ^.*\spam_pwquality.so\s(?!.*retry\s*=\s*).*$
    replace: \g<0> retry={{ var_password_pam_retry }}
  when: '"pam" in ansible_facts.packages'
  tags:
    - cat II
...
