---
- name: "DISA RHEL-07-030690: Search /etc/audit/rules.d for sudo audit rule entries"
  find:
    paths: "/etc/audit/rules.d"
    recurse: no
    contains: "^.*path=/usr/bin/sudo.*$"
    patterns: "*.rules"
  register: find_sudo
  tags:
    - cat II

- name: "DISA RHEL-07-030690: Use /etc/audit/rules.d/privileged.rules as the recipient for the rule"
  set_fact:
    all_files:
      - /etc/audit/rules.d/privileged.rules
  when: find_sudo.matched == 0 and True
  tags:
    - cat II

- name: "DISA RHEL-07-030690: Use matched file as the recipient for the rule"
  set_fact:
    all_files:
      - "{{ find_sudo.files | map(attribute='path') | list | first }}"
  when: find_sudo.matched > 0 and True
  tags:
    - cat II

- name: "DISA RHEL-07-030690: Inserts/replaces the sudo rule in rules.d"
  lineinfile:
    path: "{{ all_files[0] }}"
    line: "-a always,exit -F path=/usr/bin/sudo -F perm=x -F auid>=1000 -F auid!=unset -F key=privileged"
    create: yes
  tags:
    - cat II

- name: "DISA RHEL-07-030690: Inserts/replaces the sudo rule in /etc/audit/audit.rules"
  lineinfile:
    path: /etc/audit/audit.rules
    line: "-a always,exit -F path=/usr/bin/sudo -F perm=x -F auid>=1000 -F auid!=unset -F key=privileged"
    create: yes
  tags:
    - cat II
...   