---
- name: "DISA RHEL-07-010230: Set Password Minimum Age"
  lineinfile:
    create: yes
    path: /etc/login.defs
    regexp: ^#?PASS_MIN_DAYS
    line: "PASS_MIN_DAYS {{ var_accounts_minimum_age_login_defs }}"
  tags:
    - cat II
...