---
- name: "DISA-STIG-RHEL-07-040330: Disable SSH Support for Rhosts RSA Authentication"
  lineinfile:
    create: yes
    dest: /etc/ssh/sshd_config
    regexp: ^RhostsRSAAuthentication
    line: RhostsRSAAuthentication no
    validate: /usr/sbin/sshd -t -f %s
  tags:
    - cat II
...
