---
- name: "DISA RHEL-07-010300: Disable SSH Access via Empty Passwords"
  lineinfile:
    create: yes
    path: /etc/ssh/sshd_config
    regexp: ^PermitEmptyPasswords
    line: PermitEmptyPasswords no
    validate: /usr/sbin/sshd -t -f %s
  tags:
    - cat I
...