---
- name: "DISA RHEL-07-021300: Disable service kdump"
  service:
    name: kdump
    enabled: "no"
    state: "stopped"
  register: service_result
  failed_when: "service_result is failed and ('Could not find the requested service' not in service_result.msg)"
  tags:
   - cat II

- name: "DISA RHEL-07-021300: Disable socket of service kdump if applicable"
  service:
    name: kdump.socket
    enabled: "no"
    state: "stopped"
  register: socket_result
  failed_when: "socket_result is failed and ('Could not find the requested service' not in socket_result.msg)"
  tags:
   - cat II
...