---
- name: "DISA-STIG-RHEL-07-040360: Print last log"
  lineinfile:
    create: yes
    dest: /etc/ssh/sshd_config
    regexp: ^PrintLastLog
    line: PrintLastLog yes
    validate: /usr/sbin/sshd -t -f %s
  #notify: restart sshd
  tags:
    - cat II
...
