---
- name: "DISA RHEL-07-030380: Set architecture for audit fchown tasks"
  set_fact:
    audit_arch: "b{{ ansible_architecture | regex_replace('.*(\\d\\d$)','\\1') }}"
  tags:
    - cat II

- name: "DISA RHEL-07-030380: Search /etc/audit/rules.d for other DAC audit rules"
  find:
    paths: "/etc/audit/rules.d"
    recurse: no
    contains: "-F key=perm_mod$"
    patterns: "*.rules"
  register: find_fchown
  tags:
    - cat II

- name: "DISA RHEL-07-030380: If existing DAC ruleset not found, use /etc/audit/rules.d/privileged.rules as the recipient for the rule"
  set_fact:
    all_files:
      - /etc/audit/rules.d/privileged.rules
  when: find_fchown.matched == 0 and True
  tags:
    - cat II

- name: "DISA RHEL-07-030380: Use matched file as the recipient for the rule"
  set_fact:
    all_files:
      - "{{ find_fchown.files | map(attribute='path') | list | first }}"
  when: find_fchown.matched > 0 and True
  tags:
    - cat II

- name: "DISA RHEL-07-030380: Inserts/replaces the fchown rule in rules.d when on x86"
  lineinfile:
    path: "{{ all_files[0] }}"
    line: "-a always,exit -F arch=b32 -S fchown -F auid>=1000 -F auid!=unset -F key=perm_mod"
    create: yes
  tags:
    - cat II

- name: "DISA RHEL-07-030380: Inserts/replaces the fchown rule in rules.d when on x86_64"
  lineinfile:
    path: "{{ all_files[0] }}"
    line: "-a always,exit -F arch=b64 -S fchown -F auid>=1000 -F auid!=unset -F key=perm_mod"
    create: yes
  when: audit_arch == 'b64' and True
  tags:
    - cat II

- name: "DISA RHEL-07-030380: Inserts/replaces the fchown rule in /etc/audit/audit.rules when on x86"
  lineinfile:
    line: "-a always,exit -F arch=b32 -S fchown -F auid>=1000 -F auid!=unset -F key=perm_mod"
    state: present
    dest: /etc/audit/audit.rules
  tags:
    - cat II

- name: "DISA RHEL-07-030380: Inserts/replaces the fchown rule in audit.rules when on x86_64"
  lineinfile:
    line: "-a always,exit -F arch=b64 -S fchown -F auid>=1000 -F auid!=unset -F key=perm_mod"
    state: present
    dest: /etc/audit/audit.rules
    create: yes
  when: audit_arch == 'b64' and True
  tags:
    - cat II
...