---
- hosts: all
  become_user: root
  become: yes
  tasks:
    - name: Deploy ans ssh key
      authorized_key:
        manage_dir: yes
        state: present
        user: ans
        key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDA7Hl9HY0PkEcsFVYIvxSaYedGB29gPFJIos8SRAFgEYK70MDOfZpBSEvU18dk+FpVvv6hjGIsrgw3C8yYQl5xXmJq6xmK5VkN7mKiBtoaEW/2xUCth8908sYw2/MO/XU6/hRi0X08dfcAqGJgMe3cJMwg2woVMXaXbL5yX2o/QRFHAZr68SykRci+1AXWbNaC9GsQTYmPajQWRbmjSgn45Nwn8mCrwoVMl7r9svf8B7WlFqf8f32eIQufDXoEhtx1zjLeJkNEveHekI4CRZ+dzI+rDOKJn6Mvimh29BjZleUoYIOEtD1f/2s6AMSuAfj85UqKKLYMrgvZIdgu1zAX ans@tstsrvnox.valhalla.shortesys.com'

    - name: Install repo configs [Server]
      copy:
        src: /nfs/admin/twr_files/work/yumrepo/isosrv.repo
        dest: /etc/yum.repos.d/isosrv.repo
        owner: root
        group: root
        mode: '0640'
      when: ansible_facts['lsb']['major_release']|int == 7 && ansible_facts['lsb']['id'] == "RedHatEnterpriseServer"

    - name: Install repo configs
      copy:
        src: /nfs/admin/twr_files/work/yumrepo/isowks.repo
        dest: /etc/yum.repos.d/isowks.repo
        owner: root
        group: root
        mode: '0640'
      when: ansible_facts['lsb']['major_release']|int == 7 && ansible_facts['lsb']['id'] == "RedHatEnterpriseWorkstation"

    - name: Install prequisite packages
      yum:
        name: "{{ prereqs }}"
        state: present
      vars:
        - redhat-lsb
        - nfs-utils

    - name: Reset ans password
      user:
        name: ans
        password: '$6$2ZZEgzgX5SxiKcIb$gYjxKeow7PsS2RshZQwKKdma67YByLRkIiUVA8r5gm9gLdaHgE4p3rnStuYTs3EoeJjyt.gzf68OF8mGymq7M1'
        update_password: always
...